# Generated by Django 3.2.18 on 2023-04-19 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='GPA',
        ),
    ]
