# Generated by Django 3.2.18 on 2023-04-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='GPA',
            field=models.FloatField(default=0),
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
