# Generated by Django 3.2.18 on 2023-04-19 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20230419_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='birth_data',
        ),
        migrations.RemoveField(
            model_name='student',
            name='description',
        ),
    ]
